HealthPlus/Controllers/DoctorAdminController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using HealthPlus.Models;
using HealthPlus.Context;
using Microsoft.Ajax.Utilities;

namespace HealthPlus.Controllers
{
    public class DoctorAdminController : Controller
    {
        public DoctorAdminController()
        {
            if (System.Web.HttpContext.Current.Session["AdminId"] == null)
            {
                RedirectToAction("AdminLogin", "Authentication");
            }
        }

        private HospitalContext db = new HospitalContext();
        BaseController baseController=new BaseController();
        // GET: /DoctorAdmin/
        public ActionResult Index()
        {
            string[] days=new string[7];
            days[0] = "Sunday";
            days[1] = "Monday";
            days[2] = "Tuesday";
            days[3] = "Wednesday";
            days[4] = "Thursday";
            days[5] = "Friday";
            days[6] = "Saturday";
            

                
            List<Doctor> doctors = db.Doctor.ToList();
            foreach (Doctor doc in doctors)
            {
                string dd = "";
                doc.Name = baseController.Decrypt(doc.Name);
                doc.Degree = baseController.Decrypt(doc.Degree);
                doc.Designation = baseController.Decrypt(doc.Designation);
                doc.Email = baseController.Decrypt(doc.Email);
                int i;
                for (i = 0; i < doc.Schedule.Length-1; i++)
                {
                    if (doc.Schedule[i] != ',')
                    {
                        int ind = Convert.ToInt32(doc.Schedule[i])-48;
                        dd = dd + days[ind] + " ,  ";
                    }
                }
                dd = dd + days[Convert.ToInt32(doc.Schedule[i])-48];
                doc.Schedule = dd;
            }
            return View(doctors);
        }


        // GET: /DoctorAdmin/Details/5
       

        // GET: /DoctorAdmin/Create
        public ActionResult Create(string message)
        {
            ViewBag.Message = message;
            ViewBag.DoctorCategory=db.DoctorCategory.ToList();
            return View();
        }

        // POST: /DoctorAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Password,Designation,Degree,Fees")] Doctor doctor, HttpPostedFileBase Image, IList<int> Schedule, int CategoryId)
        {
            string s = "";
            int i;
            
            for (i = 0; i < Schedule.Count-1; i++)
            {
                s = s + Schedule[i]+",";
            }
            s = s + Schedule[i];
            doctor.Schedule = s;
            doctor.CategoryId = CategoryId;
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                    {
                        
                        try
                        {
                            string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                            string uploadUrl = Server.MapPath("~/Photos/Doctor");
                            Image.SaveAs(Path.Combine(uploadUrl, fileName));
                            doctor.Image = "Photos/Doctor/" + fileName;
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }
                    }
                doctor.Name = baseController.Encrypt(doctor.Name);
                doctor.Email = baseController.Encrypt(doctor.Email);
                doctor.Degree = baseController.Encrypt(doctor.Degree);
                doctor.Password = baseController.EncodePasswordMd5(doctor.Password);
                doctor.Designation = baseController.Encrypt(doctor.Designation);
                db.Doctor.Add(doctor);
                db.SaveChanges();
                
            }

            return RedirectToAction("Create",new{message="Doctor Successfully Appointed"});
        }

        // GET: /DoctorAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.DoctorCategory = db.DoctorCategory.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctor.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            doctor.Degree = baseController.Decrypt(doctor.Degree);
            doctor.Designation = baseController.Decrypt(doctor.Designation);
            doctor.Email = baseController.Decrypt(doctor.Email);
            doctor.Name = baseController.Decrypt(doctor.Name);
            string[] schedule = new string[7];
            int i;
            for (i = 0; i < doctor.Schedule.Length; i++)
            {
                if (doctor.Schedule[i] != ',')
                {
                    schedule[Convert.ToInt32(doctor.Schedule[i]) - 48] = "checked=\"checked\"";
                }
            }
            ViewBag.Schedule = schedule;
            return View(doctor);
        }

        // POST: /DoctorAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Email,Password,Designation,Degree,Fees")] Doctor doctor ,HttpPostedFileBase Image, IList<int> Schedule, int CategoryId,string pastImage)
        {
            if (ModelState.IsValid)
            {
                string s = "";
                int i;

                for (i = 0; i < Schedule.Count - 1; i++)
                {
                    s = s + Schedule[i] + ",";
                }
                s = s + Schedule[i];
                doctor.Schedule = s;
                doctor.CategoryId = CategoryId;

                if (Image != null && Image.ContentLength > 0)
                {
                    string fullPath = Request.MapPath("~/" + pastImage);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Photos/Doctor");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        doctor.Image = "Photos/Doctor/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    doctor.Image = pastImage;
                }

                doctor.Name = baseController.Encrypt(doctor.Name);
                doctor.Email = baseController.Encrypt(doctor.Email);
                doctor.Degree = baseController.Encrypt(doctor.Degree);
                doctor.Password = baseController.EncodePasswordMd5(doctor.Password);
                doctor.Designation = baseController.Encrypt(doctor.Designation);
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: /DoctorAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctor.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            doctor.Degree = baseController.Decrypt(doctor.Degree);
            doctor.Designation = baseController.Decrypt(doctor.Designation);
            doctor.Email = baseController.Decrypt(doctor.Email);
            doctor.Name = baseController.Decrypt(doctor.Name);
            return View(doctor);
        }

        // POST: /DoctorAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctor.Find(id);
            db.Doctor.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthPlus/Views/DoctorAdmin/Create.cshtml
@model HealthPlus.Models.Doctor

@{
    ViewBag.Title = "Create";
}
@section design{
    <style>
    .b-box {
        margin: 26px 139px;
        background-color: aliceblue;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
    }

    .bbt {
        width: 31%;
        margin-left: 21em;
    }

    .warning {
        /* color: red; */
        font-weight: 400;
        padding: 10px;
        border-radius: 9px;
        width: 28em;
        text-align: center;
        box-shadow: -1px 4px 1px 1px #34404c;
        margin-bottom: 11px;
    }

    .error {
        color: red;
    }
</style>
}

<div class="b-box">
    <center>
        @if (ViewBag.Message != null)
        {

            <div class="warning" style="background-color: #46e86d;" id="warningLabel">
                <label>@ViewBag.Message</label>
            </div>

        }
    </center>
    @using (Html.BeginForm("Create", "DoctorAdmin", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <center>
                <h4>Appoint Doctor</h4>
            </center><hr/>
            @Html.ValidationSummary(true)

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.CategoryId, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    <select name="CategoryId" class="form-control">
                        <option value="">Select Category</option>
                        @foreach (var v in ViewBag.DoctorCategory)
                        {
                            <option value="@v.Id">@v.Title</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Email, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Password, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Image, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Image, new {Type = "file"})
                    @Html.ValidationMessageFor(model => model.Image)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Designation, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Designation, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Designation)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Degree, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Degree, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Degree)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Fees, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Fees, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Fees)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Schedule, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    <table>
                        <tr>
                            <td><label for="0">Sunday:</label></td>
                            <td><input id="0" type="checkbox" name="Schedule" value="0"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="1">Monday:</label></td>
                            <td><input id="1" type="checkbox" name="Schedule" value="1"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="2">Tuesday:</label></td>
                            <td><input id="2" type="checkbox" name="Schedule" value="2"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="3">Wednesday:</label></td>
                            <td><input id="3" type="checkbox" name="Schedule" value="3"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="4">Thursday:</label></td>
                            <td><input id="4" type="checkbox" name="Schedule" value="4"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="5">Friday:</label></td>
                            <td><input id="5" type="checkbox" name="Schedule" value="5"/><br/></td>
                        </tr>
                        <tr>
                            <td><label for="6">Saturday:</label></td>
                            <td><input id="6" type="checkbox" name="Schedule" value="6"/><br/></td>
                        </tr>
                        <tr>
                            
                            <td>
                                <p class='elabel'></p>
                            </td>
                        </tr>
                    </table>



                </div>
            </div>

            <div class="form-group row">
                @*      <div class="col-md-4"></div>*@
                <div class="col-md-12" style="position: absolute; text-align: center;">
                    <input type="submit" value="Create" style="width: 23%" class="btn btn-primary"/>
                </div>
            </div>
            <div class="row">

                <div class="col-md-12" style="text-align: center; margin-top: 27px;">
                    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-warning bbt"})
                </div>
            </div>
            <div>

            </div>
        </div>
    }


</div>
@section scripts{

<script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function() {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
        $("#insertForm").validate({
            rules: {
                Name: "required",
                Email: {
                    required: true,
                    email: true
                },
                Password: {
                    required: true,
                    minlength: 5
                },

                Designation: {
                    required: true
                    
                },
                Degree: {
                    required: true,
                   
                },
               
                Fees: {
                    required: true,
                    number:true
                },
                Schedule: "required",
                CategoryId: "required",
                Image:"required"
            },
            messages: {
                Name: "Please Enter Your Name",
                Email: {
                    required: "Please Enter A New Email id",
                    email: "Email id not correct"
                },
                Password: {
                    required: "Please Enter Password",
                    minlength: "Minimum length is 5"
                },
                Image:"Please Select an Image",
                Fees: {
                    required: "Please Enter A Fee Amount",
                    number: "Fee should not contain cahracter"
                },
                Degree: {
                    required: "Please Enter Doctor's Degrees",
                    
                },
                Designation: "Please Enter Doctor's Designation",
                Schedule: "Please Select Schedule",
                CategoryId: "Please Select Category"

            },
            errorPlacement: function (error, element) {
                if (element.is(":checkbox")) {
                    error.appendTo(('.elabel'));
                }
                else { // This is the default behavior 
                    error.insertAfter(element);
                }
            }

        });
    </script>
}

HealthPlus/Views/DoctorAdmin/Edit.cshtml
@using HealthPlus.Models
@model HealthPlus.Models.Doctor

@{
    ViewBag.Title = "Create";

}
@section design{
    <style>
    .b-box {
        margin: 26px 139px;
        background-color: aliceblue;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
    }

    .bbt {
        width: 31%;
        margin-left: 21em;
    }

    .warning {
        /* color: red; */
        font-weight: 400;
        padding: 10px;
        border-radius: 9px;
        width: 28em;
        text-align: center;
        box-shadow: -1px 4px 1px 1px #34404c;
        margin-bottom: 11px;
    }

    .error {
        color: red;
    }
</style>
}

<div class="b-box">
    <center>
        @if (ViewBag.Message != null)
        {

            <div class="warning" style="background-color: #46e86d;" id="warningLabel">
                <label>@ViewBag.Message</label>
            </div>

        }
        
    </center>
    @using (Html.BeginForm("Edit", "DoctorAdmin", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <center>
                <h4>Update Doctor Info</h4>
            </center><hr />
            @Html.ValidationSummary(true)

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <select name="CategoryId" class="form-control">
                        <option value="">Select Category</option>
                        @foreach (var v in ViewBag.DoctorCategory)
                        {
                            if (v.Id == Model.CategoryId)
                            {
                                <option value="@v.Id" selected="selected">@v.Title</option>
                                continue;
                            }
                            else
                            {
                                <option value="@v.Id">@v.Title</option>
                            }
                                
                        }
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <input type="file" name="Image"/>
                    @Html.HiddenFor(model => model.Image, new {@Name="pastImage"})
                    @Html.ValidationMessageFor(model => model.Image)</div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Degree, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Degree)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Fees, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Fees, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fees)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Schedule, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <table>
                        <tr>
                            <td><label for="0">Sunday:</label></td>
                            <td><input id="0" type="checkbox" name="Schedule" value="0" @ViewBag.Schedule[0]/><br /></td>
                        </tr>
                        <tr>
                            <td><label for="1">Monday:</label></td>
                            <td><input id="1" type="checkbox" name="Schedule" value="1" @ViewBag.Schedule[1] /><br /></td>
                        </tr>
                        <tr>
                            <td><label for="2">Tuesday:</label></td>
                            <td><input id="2" type="checkbox" name="Schedule" value="2" @ViewBag.Schedule[2] /><br /></td>
                        </tr>
                        <tr>
                            <td><label for="3">Wednesday:</label></td>
                            <td><input id="3" type="checkbox" name="Schedule" value="3" @ViewBag.Schedule[3] /><br /></td>
                        </tr>
                        <tr>
                            <td><label for="4">Thursday:</label></td>
                            <td><input id="4" type="checkbox" name="Schedule" value="4" @ViewBag.Schedule[4] /><br /></td>
                        </tr>
                        <tr>
                            <td><label for="5">Friday:</label></td>
                            <td><input id="5" type="checkbox" name="Schedule" value="5" @ViewBag.Schedule[5] /><br /></td>
                        </tr>
                        <tr>
                            <td><label for="6">Saturday:</label></td>
                            <td><input id="6" type="checkbox" name="Schedule" value="6" @ViewBag.Schedule[6] /><br /></td>
                        </tr>
                        <tr>

                            <td>
                                <p class='elabel'></p>
                            </td>
                        </tr>
                    </table>



                </div>
            </div>

            <div class="form-group row">
                @*      <div class="col-md-4"></div>*@
                <div class="col-md-12" style="position: absolute; text-align: center;">
                    <input type="submit" value="Edit" style="width: 23%" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">

                <div class="col-md-12" style="text-align: center; margin-top: 27px;">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning bbt" })
                </div>
            </div>
            <div>

            </div>
        </div>
    }


</div>
@section scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
        $("#insertForm").validate({
            rules: {
                Name: "required",
                Email: {
                    required: true,
                    email: true
                },
                Password: {
                    required: true,
                    minlength: 5
                },

                Designation: {
                    required: true

                },
                Degree: {
                    required: true,

                },

                Fees: {
                    required: true,
                    number: true
                },
                Schedule: "required",
                CategoryId: "required"
                
            },
            messages: {
                Name: "Please Enter Your Name",
                Email: {
                    required: "Please Enter Email id",
                    email: "Email id not correct"
                },
                Password: {
                    required: "Please Enter Password",
                    minlength: "Minimum length is 5"
                },
               
                Fees: {
                    required: "Please Enter A Fee Amount",
                    number: "Fee should not contain cahracter"
                },
                Degree: {
                    required: "Please Enter Doctor's Degrees",

                },
                Designation: "Please Enter Doctor's Designation",
                Schedule: "Please Select Schedule",
                CategoryId: "Please Select Category"

            },
            errorPlacement: function (error, element) {
                if (element.is(":checkbox")) {
                    error.appendTo(('.elabel'));
                }
                else { // This is the default behavior
                    error.insertAfter(element);
                }
            }

        });
    </script>
}