HealthPlus/Controllers/NurseAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthPlus.Context;
using HealthPlus.Models;

namespace HealthPlus.Controllers
{
    public class NurseAdminController : Controller
    {

        public NurseAdminController()
        {
            if (System.Web.HttpContext.Current.Session["AdminId"] == null)
            {
                RedirectToAction("AdminLogin", "Authentication");
            }
        }
        private HospitalContext db = new HospitalContext();
        BaseController baseController = new BaseController();
        //
        // GET: /NurseAdmin/
        public ActionResult Index()
        {
            List<Nurse> nurses = db.Nurse.ToList();
            foreach (Nurse nurse in nurses)
            {
                nurse.Name = baseController.Decrypt(nurse.Name);
                nurse.Designation = baseController.Decrypt(nurse.Designation);
                nurse.Email = baseController.Decrypt(nurse.Email);
            }
            return View(nurses);
        }


        // GET: /NurseAdmin/Details/5


        // GET: /NurseAdmin/Create
        public ActionResult Create(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        // POST: /NurseAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Password,Designation")] Nurse nurse, HttpPostedFileBase Image)
        {
            
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Photos/Nurse");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        nurse.Image = "Photos/Nurse/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                nurse.Name = baseController.Encrypt(nurse.Name);
                nurse.Email = baseController.Encrypt(nurse.Email);

                nurse.Password = baseController.EncodePasswordMd5(nurse.Password);
                nurse.Designation = baseController.Encrypt(nurse.Designation);
                db.Nurse.Add(nurse);
                db.SaveChanges();

            }

            return RedirectToAction("Create", new { message = "Nurse Successfully Appointed" });
        }

        // GET: /NurseAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nurse nurse = db.Nurse.Find(id);
            if (nurse == null)
            {
                return HttpNotFound();
            }
            
            nurse.Designation = baseController.Decrypt(nurse.Designation);
            nurse.Email = baseController.Decrypt(nurse.Email);
            nurse.Name = baseController.Decrypt(nurse.Name);
            return View(nurse);
        }

        // POST: /NurseAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Password,Designation")] Nurse nurse, HttpPostedFileBase Image,string pastImage)
        {
            if (ModelState.IsValid)
            {
                
                if (Image != null && Image.ContentLength > 0)
                {
                    string fullPath = Request.MapPath("~/" + pastImage);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Photos/Nurse");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        nurse.Image = "Photos/Nurse/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    nurse.Image = pastImage;
                }

                nurse.Name = baseController.Encrypt(nurse.Name);
                nurse.Email = baseController.Encrypt(nurse.Email);
              
                nurse.Password = baseController.EncodePasswordMd5(nurse.Password);
                nurse.Designation = baseController.Encrypt(nurse.Designation);
                db.Entry(nurse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nurse);
        }

        // GET: /NurseAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nurse nurse = db.Nurse.Find(id);
            if (nurse == null)
            {
                return HttpNotFound();
            }
            
            nurse.Designation = baseController.Decrypt(nurse.Designation);
            nurse.Email = baseController.Decrypt(nurse.Email);
            nurse.Name = baseController.Decrypt(nurse.Name);
            return View(nurse);
        }

        // POST: /NurseAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nurse nurse = db.Nurse.Find(id);
            db.Nurse.Remove(nurse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

HealthPlus/Views/NurseAdmin/Create.cshtml
@model HealthPlus.Models.Nurse

@{
    ViewBag.Title = "Create";
}
@section design{
<style>
    .b-box {
        margin: 26px 139px;
        background-color: aliceblue;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
    }

    .bbt {
        width: 31%;
        margin-left: 21em;
    }

    .warning {
        /* color: red; */
        font-weight: 400;
        padding: 10px;
        border-radius: 9px;
        width: 28em;
        text-align: center;
        box-shadow: -1px 4px 1px 1px #34404c;
        margin-bottom: 11px;
    }

    .error {
        color: red;
    }
</style>
}

<div class="b-box">
    <center>
        @if (ViewBag.Message != null)
        {

            <div class="warning" style="background-color: #46e86d;" id="warningLabel">
                <label>@ViewBag.Message</label>
            </div>

        }
    </center>
    @using (Html.BeginForm("Create", "NurseAdmin", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <center>
                <h4>Appoint Nurse</h4>
            </center><hr/>
            @Html.ValidationSummary(true)

           

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Email, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Password, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Image, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Image, new {Type = "file"})
                    @Html.ValidationMessageFor(model => model.Image)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Designation, new {@class = "control-label col-md-2"})
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Designation, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Designation)
                </div>
            </div>

            <div class="form-group row">
               
                <div class="col-md-12" style="position: absolute; text-align: center;">
                    <input type="submit" value="Create" style="width: 23%" class="btn btn-primary"/>
                </div>
            </div>
            <div class="row">

                <div class="col-md-12" style="text-align: center; margin-top: 27px;">
                    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-warning bbt"})
                </div>
            </div>
            <div>

            </div>
        </div>
    }


</div>
@section scripts{

<script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function() {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
        $("#insertForm").validate({
            rules: {
                Name: "required",
                Email: {
                    required: true,
                    email: true
                },
                Password: {
                    required: true,
                    minlength: 5
                },

                Designation: {
                    required: true
                    
                },
               
                Image:"required"
            },
            messages: {
                Name: "Please Enter Your Name",
                Email: {
                    required: "Please Enter A New Email id",
                    email: "Email id not correct"
                },
                Password: {
                    required: "Please Enter Password",
                    minlength: "Minimum length is 5"
                },
                Image:"Please Select an Image",
                
                Designation: "Please Enter Doctor's Designation"
               
            },
            errorPlacement: function (error, element) {
                if (element.is(":checkbox")) {
                    error.appendTo(('.elabel'));
                }
                else { // This is the default behavior 
                    error.insertAfter(element);
                }
            }

        });
    </script>
}

HealthPlus/Views/NurseAdmin/Delete.cshtml
@model HealthPlus.Models.Nurse

@{
    ViewBag.Title = "Delete";
}
@section design{
    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

}

<div class="x-box-2">
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <table id="datatable" class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            
            
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                @Html.DisplayFor(item => item.Name)
            </td>
            <td>
                @Html.DisplayFor(item => item.Email)
            </td>

            <td>
                <img style="height: 98px;" src="~/@Html.DisplayFor(item => item.Image)">
            </td>
            <td>
                @Html.DisplayFor(item => item.Designation)
            </td>
            

        </tr>
        </tbody>


    </table>
    <center>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index",null,new{@class="btn btn-primary"})
            </div>
        }
    </center>
</div>
@section scripts{
    <script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        var table = $('#datatable').DataTable();
    });
</script>
}

HealthPlus/Views/NurseAdmin/Edit.cshtml
@using HealthPlus.Models
@model HealthPlus.Models.Nurse

@{
    ViewBag.Title = "Create";

}
@section design{
<style>
    .b-box {
        margin: 26px 139px;
        background-color: aliceblue;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
    }

    .bbt {
        width: 31%;
        margin-left: 21em;
    }

    .warning {
        /* color: red; */
        font-weight: 400;
        padding: 10px;
        border-radius: 9px;
        width: 28em;
        text-align: center;
        box-shadow: -1px 4px 1px 1px #34404c;
        margin-bottom: 11px;
    }

    .error {
        color: red;
    }
</style>
}

<div class="b-box">
    <center>
        @if (ViewBag.Message != null)
        {

            <div class="warning" style="background-color: #46e86d;" id="warningLabel">
                <label>@ViewBag.Message</label>
            </div>

        }
        
    </center>
    @using (Html.BeginForm("Edit", "NurseAdmin", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <center>
                <h4>Edit Nurse Informations</h4>
            </center><hr />
            @Html.ValidationSummary(true)

            

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <input type="file" name="Image"/>
                    @Html.HiddenFor(model => model.Image, new {@Name="pastImage"})
                    @Html.ValidationMessageFor(model => model.Image)</div>
            </div>

            <div class="form-group row">
                <div class="col-md-2"> </div>
                @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation)
                </div>
            </div>
            <div class="form-group row">
                @*      <div class="col-md-4"></div>*@
                <div class="col-md-12" style="position: absolute; text-align: center;">
                    <input type="submit" value="Edit" style="width: 23%" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">

                <div class="col-md-12" style="text-align: center; margin-top: 27px;">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning bbt" })
                </div>
            </div>
            <div>

            </div>
        </div>
    }


</div>
@section scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
        $("#insertForm").validate({
            rules: {
                Name: "required",
                Email: {
                    required: true,
                    email: true
                },
                Password: {
                    required: true,
                    minlength: 5
                },

                Designation: {
                    required: true

                }
                
                
            },
            messages: {
                Name: "Please Enter Your Name",
                Email: {
                    required: "Please Enter Email id",
                    email: "Email id not correct"
                },
                Password: {
                    required: "Please Enter Password",
                    minlength: "Minimum length is 5"
                },
                Designation: "Please Enter Doctor's Designation"
               

            }

        });
    </script>
}

HealthPlus/Views/NurseAdmin/Index.cshtml
@model IEnumerable<HealthPlus.Models.Nurse>

@{
    ViewBag.Title = "Index";
}
@section design{
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
    .col-sz {
        width: 100px;
    }

    .wd {
        width: 100%;
    }
</style>

}

<div class="x-box-2">
    <center>
        <p>
            @Html.ActionLink("Appoint New Nurse", "Create",null,new {@class="newbox btn btn-primary"})
        </p>
    </center>
    <table id="datatable" class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            
            <th>
                Action
            </th>
        </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    <img style="height: 98px;" src="~/@Html.DisplayFor(modelItem => item.Image)">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary wd" }) <br/>

                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger wd" })
                </td>
            </tr>
        }

    </table>

</div>

@section scripts{
<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
    <script>
    $(document).ready(function () {
    var table = $('#datatable').DataTable();
    });
    </script>
}