HealthPlus/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Web;
using System.Web.Mvc;
using HealthPlus.Context;
using HealthPlus.Models;

namespace HealthPlus.Controllers
{
    public class AdminController : Controller
    {
        BaseController baseController=new BaseController();
        //
        // GET: /Admin/
        public ActionResult PatientAdmitWard()
        {
            ViewBag.PatientAdmitWard = "active";
            List<Ward> wards;
            using (var ctx = new HospitalContext())
            {
                wards = ctx.Ward.ToList();
            }
             
            return View(wards);
        }

        public JsonResult GetPatientByWard(int id)
        {
            List<Prescription> prescriptions = new List<Prescription>();
            using (var ctx = new HospitalContext())
            {
                var q = from a in ctx.Appointment
                    join p in ctx.Patient
                        on a.PatientId equals p.Id
                    join d in ctx.Doctor
                        on a.DoctorId equals d.Id
                    where a.WardId == id
                    select new
                    {
                        aId=a.Id,
                        PName = p.Name,
                        PAge = p.Age,
                        pAddress = p.Address,
                        DName = d.Name,
                        Presc = a.Prescription
                    };

                foreach (var k in q)
                {
                    Prescription p = new Prescription();
                    p.Id = k.aId;
                    p.PatientName = baseController.Decrypt(k.PName);
                    p.DoctorName = baseController.Decrypt(k.DName);
                    p.PatientAge = k.PAge;
                    p.PatientAddress = baseController.Decrypt(k.pAddress);
                    p.Prescript = k.Presc;
                    prescriptions.Add(p);
                }
            }
            return Json(prescriptions);
        }

        public ActionResult ReleasePatient(int id, int wardId)
        {
            using (var ctx = new HospitalContext())
            {
                Appointment ap = ctx.Appointment.Find(id);
                ap.WardId = 0;
                ctx.SaveChanges();
            }
            return Json(1);
        }

        public ActionResult AssignNurse()
        {
            ViewBag.AssignNurse = "active";
            List<Ward> wards;
            List<Nurse> nurse=new List<Nurse>();
            using (var ctx=new HospitalContext())
            {
               var nur = ctx.Nurse.Where(c => c.WardId == 0).Select(c=>new {c.Name,c.Id}).ToList();
                foreach (var nn in nur)
                {
                    Nurse n = new Nurse();
                    n.Name = baseController.Decrypt(nn.Name);
                    n.Id = nn.Id;
                    nurse.Add(n);

                }
                ViewBag.Nurse = nurse;
                wards = ctx.Ward.ToList();
            }
            return View(wards);
        }

        public ActionResult DeAssignNurse(int id)
        {
            using (var ctx = new HospitalContext())
            {
                Nurse n=ctx.Nurse.Find(id);
                n.WardId = 0;
                ctx.SaveChanges();
            }
            return Json(1);

        }

       
        public ActionResult GetNurseByWard(int id)
        {
            List<Nurse> nurse;
            using (var ctx = new HospitalContext())
            {
                nurse = ctx.Nurse.Where(c => c.WardId == id).ToList();
            }
            foreach (Nurse n in nurse)
            {
                n.Name = baseController.Decrypt(n.Name);
                n.Designation = baseController.Decrypt(n.Designation);
                
            }
            return Json(nurse);
        }

        public ActionResult AssignNurseToWard(int nurseId,int wardId)
        {
            using (var ctx = new HospitalContext())
            {
               Nurse nurse = ctx.Nurse.Find(nurseId);
                nurse.WardId = wardId;
                ctx.SaveChanges();
            }
            return Json(1);
        }
    }
}

HealthPlus/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthPlus.Context;
using HealthPlus.Models;
using Rotativa.MVC;

namespace HealthPlus.Controllers
{
    public class DoctorController : Controller
    {
        BaseController baseControl = new BaseController();
        //
        // GET: /Doctor/
        public ActionResult PrescribePatient()
        {
            ViewBag.PrescribePatient = "active";
            List<Ward> wards;
            using (var ctx =new HospitalContext())
            {
                wards = ctx.Ward.ToList();
            }
            
            return View(wards);
        }

        public JsonResult GetPatient(int id)
        {
            List<PatientAppointmentView> pt = new List<PatientAppointmentView>();
            int doc = (int)Session["DoctorId"];
            string date = DateTime.Today.ToString("MM/dd/yyyy");
            using (var ctx = new HospitalContext())
            {
                var data = from a in ctx.Appointment
                    join p in ctx.Patient
                        on a.PatientId equals p.Id
                    where a.DoctorId == doc && a.Session==id && a.Approval==1 && a.Date==date
                    orderby a.SerialNo ascending 
                    select new
                    {
                        pId=a.Id,
                        pName = p.Name,
                        pAge = p.Age,
                        pNote = a.Note
                    };
                foreach (var dc in data)
                {
                    PatientAppointmentView p = new PatientAppointmentView();
                    p.AppointmentId = dc.pId;
                    p.Name = baseControl.Decrypt(dc.pName);
                    p.Age = dc.pAge;
                    p.Note = baseControl.Decrypt(dc.pNote);
                    pt.Add(p);
                }
            }
            return Json(pt);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult PrescribePatient(Prescription prescription,int AppointmentId)
        {
            ViewBag.PrescribePatient = "active";
            string name;
            name = DateTime.Now.ToString("dd-MM-yyyy") + "_" + prescription.PatientId + "_" + Guid.NewGuid() + ".pdf";
            using (var ctx = new HospitalContext())
            {
                Appointment apt = ctx.Appointment.Find(AppointmentId);
                apt.Chat = baseControl.Encrypt(prescription.Chat);
               
                if (prescription.WardId > 0)
                {
                   
                    apt.WardId = prescription.WardId;
                    
                }
                ctx.SaveChanges();
                var kl = from a in ctx.Appointment
                    join p in ctx.Patient
                        on a.PatientId equals p.Id
                    join d in ctx.Doctor
                        on a.DoctorId equals d.Id
                    where a.Id == AppointmentId
                    select new
                    {
                        DoctorName= d.Name,
                        DoctorDesignation=d.Designation,
                        DoctorDegree=d.Degree,
                        PatientName=p.Name,
                        PatientPhone=p.PhoneNo,
                        PatientAge=p.Age
                    };
                foreach (var v in kl)
                {
                    prescription.DoctorDesignation = baseControl.Decrypt(v.DoctorDesignation);
                    prescription.DoctorName = baseControl.Decrypt(v.DoctorName);
                    prescription.DoctorDegree = baseControl.Decrypt(v.DoctorDegree);
                    prescription.PatientName = baseControl.Decrypt(v.PatientName);
                    prescription.PatientAge = v.PatientAge;
                    prescription.PatientPhone = baseControl.Decrypt(v.PatientPhone);
                }

                Appointment ap = ctx.Appointment.Single(c => c.Id == AppointmentId);
                ap.Prescription = "PatientPrescriptions/"+name;
                ap.Approval = 3;
                ctx.SaveChanges();
            }
            
            var printpdf = new ActionAsPdf("MakePdf", prescription) { FileName = name };
            string path = Server.MapPath("~/PatientPrescriptions");
            string pth = Path.Combine(path, name);
            var byteArray = printpdf.BuildPdf(ControllerContext);
            var fileStream = new FileStream(pth, FileMode.Create, FileAccess.Write);
            fileStream.Write(byteArray, 0, byteArray.Length);
            fileStream.Close();
            return printpdf;

        }
        public ActionResult MakePdf(Prescription idPrescription)
        {
            return View(idPrescription);
        }

        public ActionResult Showhistory(int id)
        {
            List<Appointment>al=new List<Appointment>();

            using (var ctx=new HospitalContext())
            {
                int k = ctx.Appointment.Where(c => c.Id == id).Select(c => c.PatientId).FirstOrDefault();
                var dt=ctx.Appointment.Where(c => c.PatientId == k && c.Approval==3).Select(c => new {c.Chat, c.Prescription,c.Date});
                foreach (var d in dt)
                {
                    Appointment ap=new Appointment();
                    ap.Prescription = d.Prescription;
                    ap.Chat = baseControl.Decrypt(d.Chat);
                    ap.Date = d.Date;

                    al.Add(ap);
                }
                ViewBag.PatientId = k;
            }
            return View(al);
        }

        public JsonResult GetFilteredHistory(string datet,int Patient)
        {
            List<Appointment> al = new List<Appointment>();
            var ctx = new HospitalContext();
            SqlConnection connection = new SqlConnection(ctx.Database.Connection.ConnectionString);
            string query1 = "SELECT Chat,Prescription,Date " +
                            "FROM Appointments as a " +
                            "WHERE a.Date>='" + datet + "' AND a.PatientId<='" + Patient + "' AND a.Approval=3 ";
                           
            
            SqlCommand command = new SqlCommand(query1, connection);
           
            connection.Open();
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                Appointment ap = new Appointment();
                ap.Prescription = reader["Prescription"].ToString();
                ap.Chat = baseControl.Decrypt(reader["Chat"].ToString());
                ap.Date = reader["Date"].ToString();

                al.Add(ap);
                
            }

            reader.Close();
            ViewBag.PatientId = Patient;
            return Json(al);
        }
	}
}

HealthPlus/Controllers/PrimaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using HealthPlus.Context;
using HealthPlus.Models;
using Rotativa;
using Rotativa.MVC;

namespace HealthPlus.Controllers
{
    public class PrimaryController : Controller
    {

        public PrimaryController()
        {
            

            if (System.Web.HttpContext.Current.Session["PatientId"] != null)
            {
                int iid = (int)System.Web.HttpContext.Current.Session["PatientId"];

                using (var ctx = new HospitalContext())
                {
                    int not = ctx.Appointment.Where(c => c.PatientId == iid && c.IsSeen == 2).Select(c => c.Id).ToList().Count;

                    System.Web.HttpContext.Current.Session["PatientNotify"] = not;
                }
            }
        }

        BaseController baseController=new BaseController();
        public ActionResult Index()
        {
            ViewBag.Index = "active";
            List<Service> services;
            using (var ctx = new HospitalContext())
            {

                services = ctx.Service.ToList();
            }
            return View(services);
        }

        public ActionResult Appointment(int? val)
        {
            ViewBag.Appointment = "active";
            List<DoctorCategory> doctorCategories;
            
            List<Doctor> dc=new List<Doctor>();
            using (var ctx = new HospitalContext())
            {

                doctorCategories = ctx.DoctorCategory.ToList();
                var doctors = ctx.Doctor.OrderBy(r => Guid.NewGuid()).Select(c => new { c.Id, c.Name, c.Degree, c.Designation, c.Fees, c.Image, c.Schedule }).Take(8);
                foreach (var doc in doctors)
                {
                    Doctor doct =new Doctor();
                    doct.Id = doc.Id;
                    doct.Name = baseController.Decrypt(doc.Name);
                    doct.Degree = baseController.Decrypt(doc.Degree);
                    doct.Designation = baseController.Decrypt(doc.Designation);
                    doct.Fees = doc.Fees;
                    doct.Image = doc.Image;
                    doct.Schedule = doc.Schedule;
                    dc.Add(doct);
                }
            }
            
            ViewBag.Category = doctorCategories;
            ViewBag.Doctor = dc;
            ViewBag.Message = val;
            return View();
        }


        [HttpPost]
        public JsonResult GetAllDocById(int id)
        {
           
            List<Doctor> Dlist = new List<Doctor>();
            using (var ctx = new HospitalContext())
            {
                var k = ctx.Doctor.Where(c=>c.CategoryId==id).Select(c=>new {c.Id,c.Name,c.Designation,c.Degree,c.Image,c.Fees,c.Schedule}).ToList();
                foreach (var dc in k)
                {
                    Doctor d = new Doctor();
                    d.Id = dc.Id;
                    d.Name = baseController.Decrypt(dc.Name);
                    d.Image = dc.Image;
                    d.Designation = baseController.Decrypt(dc.Designation);
                    d.Degree = baseController.Decrypt(dc.Degree);
                    d.Fees = dc.Fees;
                    d.Schedule = dc.Schedule;
                    Dlist.Add(d);
                }
            }
           
            return Json(Dlist);

        }

        public ActionResult Emergency()
        {
            ViewBag.Emergency = "active";
            return View();
        }

        public ActionResult BloodBank()
        {
            
            return View();
        }

        public ActionResult GetBlood(string id)
        {
            List<Blood> Dlist = new List<Blood>();
            using (var ctx = new HospitalContext())
            {
                var k = ctx.Blood.Where(c => c.BloodGroup == id).Select(c => new {  c.Name,c.Address,c.Phone }).ToList();
                foreach (var dc in k)
                {
                    Blood d = new Blood();
                    d.Name = dc.Name;
                    d.Address = dc.Address;
                    d.Phone = dc.Phone;
                    Dlist.Add(d);
                }
            }

            return Json(Dlist);
        }
      
	}
}

HealthPlus/Views/Shared/_Layout.cshtml
@using System.Drawing.Printing
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/x-icon" href="~/Photos/favicon.ico"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> HealthPlus+</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("design", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <style>
        .dropdown-menu {
            left: 57em;
            padding: 9px;
            color: black;
        }
        
        </style>
</head>
<body>
<div style="background-color: #d6dee4; margin-right: 0px;" class="row gone">
    <div class="col-md-1"></div>
    <div class="col-md-3" style="margin-right: -104px;">
        <i class=" fa fa-address-book">
        </i>
        <b>Emergency: </b>01755001451
    </div>
    <div class="col-md-2">
        <span class="fa fa-envelope"></span>
        refatkhan93@gmail.com
    </div>
    <div class="col-md-4"></div>

    <div class="col-md-2">
        <span class="fa fa-map-marker"></span>
        BGCMed,Chittagong
    </div>
</div>
<nav style="background-color: #34404c;" class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand myclass animated jello" href="@Url.Action("Index","Primary")">
        <i style="font-size: 47px;" class="logo fa fa-stethoscope"></i>
        Health Plus+
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="menual collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        @if (Session["PatientId"] == null && Session["DoctorId"]==null && Session["ReceptionistId"]==null && Session["AdminId"]==null)
        {
        <div class="navbar-nav">
            <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index","Primary")">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link  @ViewBag.Appointment" href="@Url.Action("Appointment", "Primary")">Doctor</a>
            <a class="nav-item nav-link @ViewBag.Emergency" href="@Url.Action("Emergency", "Primary")">Emergency</a>
            <a class="nav-item nav-link @ViewBag.Contact" href="#">Contact</a>
            <a class="nav-item nav-link  @ViewBag.Login" href="@Url.Action("Login","Authentication")">Login</a>
            <a class="nav-item nav-link  @ViewBag.Register" href="@Url.Action("Register","Authentication")">Register</a>
        </div>
        }
        @if (Session["PatientId"] != null)
        {
            <div class="navbar-nav">
                <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index","Primary")">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link  @ViewBag.Appointment" href="@Url.Action("Appointment", "Primary")">Appointment</a>
                <a class="nav-item nav-link @ViewBag.Emergency" href="@Url.Action("Emergency", "Primary")">Emergency</a>
                <a class="nav-item nav-link @ViewBag.Contact" href="#">Contact</a>
                <a  id="Patient" class="nav-item nav-link  @ViewBag.PatientProfile" href="@Url.Action("Profile", "Patient")">Profile <sup><span id="pnof" style="display: none;" class="notif fa fa-bell"> @Session["PatientNotify"]</span></sup></a>
                <ul id="PatientProfile" class="dropdown-menu"  style="display: none"></ul>
                <a class="nav-item nav-link " href="@Url.Action("PatientLogout","Authentication")">Logout</a>
            </div>
        }
        @if (Session["DoctorId"] != null)
        {
            <div class="navbar-nav">
                <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index","Primary")">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link  @ViewBag.PrescribePatient" href="@Url.Action("PrescribePatient","Doctor")">Prescribe Patient</a>
                <a class="nav-item nav-link @ViewBag.Emergency" href="@Url.Action("Emergency", "Primary")">Emergency</a>
                <a class="nav-item nav-link @ViewBag.Contact" href="#">Contact</a>
                <a class="nav-item nav-link  @ViewBag.DoctorProfile" href="#">Profile</a>
                <a class="nav-item nav-link " href="@Url.Action("DoctorLogout","Authentication")">Logout</a>
                
            </div>
        }
        @if (Session["ReceptionistId"] != null)
        {
            <div class="navbar-nav">
                <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index","Primary")">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link  @ViewBag.AppointmentSchedule" href="@Url.Action("AppointmentSchedule", "Receptionist")">Appointment Schedule</a>
                <a class="nav-item nav-link @ViewBag.MakeBill" href="@Url.Action("MakeBill", "Receptionist")">Make Bill</a>
                <a class="nav-item nav-link  @ViewBag.Report" href="@Url.Action("Report", "Receptionist")">Report</a>
                <a class="nav-item nav-link  @ViewBag.ReceptionistProfile" href="@Url.Action("ReceptionistProfile", "Receptionist")">Profile</a>
                <a class="nav-item nav-link " href="@Url.Action("ReceptionistLogout","Authentication")">Logout</a>
                
            </div>
        }
        @if (Session["AdminId"] != null)
        {
            <div class="navbar-nav">
                <a class="nav-item nav-link @ViewBag.Doctor" href="@Url.Action("Index","DoctorAdmin")">Doctor <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link  @ViewBag.Nurse" href="@Url.Action("Index", "NurseAdmin")">Nurse</a>
                <a class="nav-item nav-link @ViewBag.PatientAdmitWard" href="@Url.Action("PatientAdmitWard", "Admin")">Ward Info</a>
                <a class="nav-item nav-link @ViewBag.AssignNurse" href="@Url.Action("AssignNurse", "Admin")">Nurse Duty</a>
                <a class="nav-item nav-link @ViewBag.Emergency" href="@Url.Action("Emergency", "Primary")">Contact</a>
                 <a class="nav-item nav-link " href="@Url.Action("AdminLogout","Authentication")">Logout</a>
            </div>
        }
    </div>
</nav>

<div class="body-content">
    @RenderBody()
    <hr/>


</div>
<footer class="footer row">
    <div class="footer-left col-md-4 col-sm-6">
        <p class="about">
            <span> About the hospital</span> Ut congue augue non tellus bibendum, in varius tellus condimentum. In scelerisque nibh tortor, sed rhoncus odio condimentum in. Sed sed est ut sapien ultrices eleifend. Integer tellus est, vehicula eu lectus tincidunt,
            ultricies feugiat leo. Suspendisse tellus elit, pharetra in hendrerit ut, aliquam quis augue. Nam ut nibh mollis, tristique ante sed, viverra massa.
        </p>
        <div class="icons">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-google-plus"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
    <div class="footer-center col-md-4 col-sm-6">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span> BGCMed,Chandonaish</span> Chittagong, Bangladesh
            </p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p> (+88) 0175 500 1451</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="#"> medservice@health.com</a>
            </p>
        </div>
    </div>
    <div class="footer-right col-md-4 col-sm-6">
        <h2> Health<span> Plus+</span></h2>
        
        <p class="name"> HealthPlus+ &copy; 2019</p>
    </div>
</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<script>
  
        var k = parseInt($('#pnof').html());
        if (k > 0) {
            $('#pnof').show();
        }
        $("#Patient").hover(function () {
            var k;
           
            var clr;
            $.ajax({
                type: "POST",
                url: '@Url.Action("HoverResult", "Patient")',
                contentType: 'application/json',
                
                success: function (response) {
                    console.log(response);
                    if(response.length !== 0)
                    $('#PatientProfile').show();
                    $.each(response, function (key, value) {
                        if (value.Approval === 1) {
                            k = "Approved";
                            clr = "Green";
                        }
                           
                        else if (value.Approval === 2) {
                            k = "Rejected";
                            clr = "Red";
                        }
                           

                        $('#PatientProfile').append("<li style=\"border-bottom: 1px solid black; margin-bottom:5px; color:"+clr+";\">Appointment to "+value.Name+" is "+k+"</li>");


                    });
                    
                }
            });
        }, function () {
                $('#PatientProfile').html("");
                $('#PatientProfile').hide();
            
           
        });
  
</script>

</body>
</html>